import sgMail from '@sendgrid/mail';

// Initialize SendGrid
sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  from?: string;
}

/**
 * Send email via SendGrid
 */
export async function sendEmail(options: EmailOptions): Promise<boolean> {
  try {
    const msg = {
      to: options.to,
      from: options.from || 'applications@innovativeautomations.dev', // Verified SendGrid sender
      subject: options.subject,
      html: options.html,
    };

    await sgMail.send(msg);
    console.log('✅ Email sent successfully to:', options.to);
    return true;
  } catch (error: any) {
    console.error('❌ Email sending failed:', error);
    if (error.response) {
      console.error('SendGrid error:', error.response.body);
    }
    return false;
  }
}

/**
 * Send investigation report email
 */
export async function sendReportEmail(data: {
  recipient: string;
  targetName: string;
  legitimacyScore: number;
  recommendation: string;
  reportUrl: string;
  executiveSummary: string;
}): Promise<boolean> {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #1e40af; color: white; padding: 30px; text-align: center; }
        .content { background: #f9fafb; padding: 30px; }
        .score-box { background: white; border-left: 4px solid #1e40af; padding: 20px; margin: 20px 0; }
        .button { display: inline-block; background: #2563eb; color: white; padding: 12px 30px;
                  text-decoration: none; border-radius: 6px; margin: 20px 0; }
        .footer { text-align: center; color: #6b7280; font-size: 12px; padding: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🔍 Investigation Complete</h1>
        </div>

        <div class="content">
          <h2>${data.targetName}</h2>

          <div class="score-box">
            <h3>Investigation Results</h3>
            <p><strong>Legitimacy Score:</strong> ${data.legitimacyScore}/10</p>
            <p><strong>Recommendation:</strong> ${data.recommendation.replace(/_/g, ' ')}</p>
          </div>

          <h3>Executive Summary</h3>
          <p>${data.executiveSummary}</p>

          <div style="text-align: center;">
            <a href="${data.reportUrl}" class="button">Download Full Report (PDF)</a>
          </div>

          <p style="margin-top: 30px; font-size: 14px; color: #6b7280;">
            This comprehensive investigation report includes detailed analysis, red flags,
            legitimacy indicators, risk assessment, and actionable recommendations.
          </p>

          <p style="margin-top: 20px; padding: 15px; background: #fef3c7; border-left: 4px solid #f59e0b; font-size: 14px;">
            <strong>Note:</strong> Additional information may be requested in the next stage of this inquiry
            to provide a more comprehensive analysis.
          </p>
        </div>

        <div class="footer">
          <p>This report is confidential and generated by InvestigatorAI</p>
          <p>© ${new Date().getFullYear()} InvestigatorAI. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `;

  return sendEmail({
    to: data.recipient,
    subject: `Investigation Complete: ${data.targetName}`,
    html,
  });
}

/**
 * Send form invitation email
 */
export async function sendFormInvitation(data: {
  recipient: string;
  clientName?: string;
  formTitle: string;
  formUrl: string;
  expiresAt?: string;
}): Promise<boolean> {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #1e40af; color: white; padding: 30px; text-align: center; }
        .content { background: #f9fafb; padding: 30px; }
        .button { display: inline-block; background: #2563eb; color: white; padding: 15px 40px;
                  text-decoration: none; border-radius: 6px; margin: 20px 0; font-size: 16px; }
        .footer { text-align: center; color: #6b7280; font-size: 12px; padding: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📋 Investigation Form Invitation</h1>
        </div>

        <div class="content">
          ${data.clientName ? `<p>Hello ${data.clientName},</p>` : '<p>Hello,</p>'}

          <p>You've been invited to complete an investigation form:</p>

          <h2 style="color: #1e40af;">${data.formTitle}</h2>

          <p>Please click the button below to access and complete the form:</p>

          <div style="text-align: center;">
            <a href="${data.formUrl}" class="button">Complete Form</a>
          </div>

          ${data.expiresAt ? `<p style="color: #dc2626;"><strong>Note:</strong> This link expires on ${data.expiresAt}</p>` : ''}

          <p style="margin-top: 30px; font-size: 14px; color: #6b7280;">
            After you submit the form, our AI will conduct a comprehensive investigation
            and you'll receive a detailed report via email.
          </p>

          <p style="margin-top: 20px; padding: 15px; background: #fef3c7; border-left: 4px solid #f59e0b; font-size: 14px;">
            <strong>Note:</strong> Additional information may be requested in the next stage of this inquiry
            to provide a more comprehensive analysis.
          </p>
        </div>

        <div class="footer">
          <p>Powered by InvestigatorAI</p>
          <p>© ${new Date().getFullYear()} InvestigatorAI. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `;

  return sendEmail({
    to: data.recipient,
    subject: `Complete Investigation Form: ${data.formTitle}`,
    html,
  });
}
